# Generated by Django 2.2.1 on 2019-06-02 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rating', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'movies',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movieapp.Movie')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'theaters',
                'db_table': 'theater',
            },
        ),
    ]
